baseurl = "/"
title = "openEuler"
theme = "project"
themesDir = "./themes"
# Site language. Available translations in the theme's `/i18n` directory.
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

uglyURLs = true

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="news"
    name = "News"
    url  = "/news.html"
    weight = 2

[[menu.main]]
    identifier = "docs"
    name = "DOCS"
    url  = "/docs/home.html"
    weight = 3

[[menu.main]]
    identifier = "download"
    name = "Download"
    url  = "/download.html"
    weight = 4


# [[menu.main]]
#    identifier = "faq"
#    name = "FAQ"
#    url  = "/faq.html"
#    weight = 5

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact.html"
    weight = 6

[[menu.main]]
    identifier = "lang"
    name = "中文"
    url = "../zh"
    weight = 7

# Menu chinese
[[languages.zh.menu.main]]
    dentifier="home"
    name = "主页"
    url  = "/zh"
    weight = 1

[[languages.zh.menu.main]]
    identifier="news"
    name = "新闻"
    url  = "/zh/news.html"
    weight = 2

[[languages.zh.menu.main]]
    identifier = "docs"
    name = "文档"
    url  = "/zh/docs/home.html"
    weight = 3

[[languages.zh.menu.main]]
    identifier = "download"
    name = "下载"
    url  = "/zh/download.html"
    weight = 4

[[languages.zh.menu.main]]
    identifier = "contact"
    name = "联系我们"
    url  = "/zh/contact.html"
    weight = 6

[[languages.zh.menu.main]]
    identifier = "lang"
    name = "EN"
    url = "/"
    weight = 7

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://gitee.com/openeuler"
    pre = "<i class='fa fa-2x fa-github'></i>"


[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:freesky.edward@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/news/"
    author = "openEuler"
    defaultKeywords = ["devows", "hugo", "go", "openEuler"]
    defaultDescription = "Site template made by devcows Modified by openEuler team"

    # Twitter
    # twitter = "GoHugoIO"
    # twitterImage = "img/twitter-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Enable the contact form by entering your Formspree.io email
    email = "contact@openeuler.io"
    contact_form_ajax = false

    about_us = "<p>We are an open source orgnization provides open source software.</p>"
    copyright = "Copyright (c) 2019 - 2020, openEuler; all rights reserved. <br /> The openEuler has registered <span>trademarks</span> and uses trademarks. For a list of trademarks of the openEuler, please see our Trademark Usage page. <span>Privacy Policy</span> and <span>Terms of Use</span>"

    # Format dates with Go's time formatting
    date_format = "January 2, 2019"

    logo = "img/openeuler.png"
    logo_small = "img/openeuler.png"
    address = """<p><strong>openEuler, io.</strong>
        <br>
        <br>Newtown upon River
        <br>Beijing
        <br>
        <strong>China</strong>
      </p>
      """
    #latitude = "-12.043333"
    #longitude = "-77.028333"
    
    ### DOC Configurations
    BookRepo = 'https://gitee.com/openeuler/docs'
    BookEditPath= 'blob/master/content'
    BookDateFormat = 'Jan 2, 2019'
    enableGitInfo = true
    BookMenuBundle = '/menu'
    bookHidden = true
    bookFlatSection = true

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us by freesky.edward@gmail.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.cards]
    enable = true

[params.emails]
    enable = true

[params.news]
    enable = true

[params.events]
    enable = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to contribute?"
    subtitle = "We apprecite your contribution, whill all related projects are open source."
    link_url = "https://gitee.com/openeuler/"
    link_text = "Go To Source"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Partners"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our news"
    subtitle = "There are many events ocur since we announce open source, Please keep an your eye on us."

[languages]

[languages.en]
    languageCode = "en-us"

[languages.zh]
    languageCode = "zh-cn"
